#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 10 13:36:45 2022

@author: gabecata
"""
import matplotlib.pyplot as plt


labels = 'Shots', 'Single Liquor Drinks','2-Liquor Drinks', '3-Liquor Drinks', '4 or More Liquor Drinks'
sizes = [23,43,42,4,12]
 

fig1, ax1 = plt.subplots()
explode = (0.05, 0.05, 0.05, 0.05, 0.05)

colors = ['yellow', 'b', 'green', 'cyan','red']

ax1.pie(sizes, colors=colors, explode=explode, labels=labels,autopct='%1.1f%%',
        shadow=True, startangle=33)
ax1.legend(loc = "lower left", bbox_to_anchor = (1, 0, 0.05, 1))
plt.title('Cocktails based on number of liquor in a drink')

plt.show()
